# Generated by Django 5.2.7 on 2026-05-30 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0005_alter_cidade_options_alter_estado_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='portal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='anuncios', to='anuncios.portal', verbose_name='Portal de Origem'),
        ),
    ]
