# Generated by Django 5.2.7 on 2026-06-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0006_alter_anuncio_portal'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='metadados',
            field=models.JSONField(blank=True, default=dict, help_text='Atributos variáveis do veículo. Ex: {"motor": "1.6", "original": true}', verbose_name='Metadados técnicos'),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='dados_externos',
            field=models.JSONField(blank=True, default=dict, verbose_name='Dados de contato/origem'),
        ),
    ]
