# Generated by Django 5.2.7 on 2026-06-08 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anuncios', '0007_anuncio_metadados_alter_anuncio_dados_externos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_snapshot', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_retido', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('proposta_enviada', 'Proposta enviada'), ('pagamento_retido', 'Pagamento retido'), ('em_transferencia', 'Em transferência'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='rascunho', max_length=32)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='anuncios.anuncio', verbose_name='Anúncio')),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to=settings.AUTH_USER_MODEL, verbose_name='Comprador')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
